apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapy-deployment
  labels:
    app: scrapy-news
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scrapy-news
  template:
    metadata:
      labels:
        app: scrapy-news
    spec:
      containers:
      - name: scrapy-news
        image: aunews-scrapy
        imagePullPolicy: Always
        resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "500Mi"
#      nodeSelector:
#        cloud.google.com/gke-nodepool: non-vespa