apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: search-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - s.ausnews.org
    - m.ausnews.org
    secretName: ausnews-tls
  rules:
  - host: s.ausnews.org
    http:
      paths:
      - backend:
          serviceName: web-api-service
          servicePort: 80
  - host: m.ausnews.org
    http:
      paths:
      - backend:
          serviceName: monitoring-service 
          servicePort: 80

