apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: search-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: vespa-web
    networking.gke.io/managed-certificates: vespa-web
spec:
  backend:
    serviceName: web-api-service
    servicePort: 80
