apiVersion: apps/v1
kind: Deployment
metadata:
  name: augmenter
  labels:
    app: augmenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: augmenter
  template:
    metadata:
      labels:
        app: augmenter
    spec:
      containers:
      - name: augmenter
        image: aunews-augmenter
        env:
          - name: TWITTER_API_KEY
            valueFrom:
              secretKeyRef:
                name: twitter-secrets
                key: api-key
          - name: TWITTER_API_SECRET
            valueFrom:
              secretKeyRef:
                name: twitter-secrets
                key: api-secret
        imagePullPolicy: Always
        resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "256Mi"
#      nodeSelector:
#        cloud.google.com/gke-nodepool: non-vespa