# Copyright Verizon Media. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
apiVersion: v1
kind: ConfigMap
metadata:
  name: vespa-config
data:
  VESPA_CONFIGSERVERS: "vespa-0.vespa-internal.default.svc.cluster.local"
