name: Build and deploy spiders

on:
  workflow_dispatch:
  push:
    paths:
    - 'crawler/**'

env:
  IMAGE: aunews-scrapy
  DEPLOYMENT_NAME: scrapy-deployment
  #todo: move these to k8s secrets
  TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
  TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
  TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET}}

defaults:
  run:
    shell: bash
    working-directory: ./crawler

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy Web API
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.LINODE_KUBE_CONFIG }}

    # Build the Docker image
    - name: Build Docker image
      run: |-
        sed -i "s/TWITTER_API_KEY/$TWITTER_API_KEY/g"  ./RISJbot/pipelines/twitterstats.py
        sed -i "s/TWITTER_API_SECRET/$TWITTER_API_SECRET/g"  ./RISJbot/pipelines/twitterstats.py
        sed -i "s/TWITTER_BEARER_TOKEN/$TWITTER_BEARER_TOKEN/g"  ./RISJbot/pipelines/twitterstats.py
        sed -i "s/TWITTER_ACCESS_TOKEN_SECRET/$TWITTER_ACCESS_TOKEN_SECRET/g"  ./RISJbot/pipelines/twitterstats.py
        sed -i "s/TWITTER_ACCESS_TOKEN/$TWITTER_ACCESS_TOKEN/g"  ./RISJbot/pipelines/twitterstats.py
        echo "$PATH"
        docker build --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image
    - name: Deploy
      run: |-
        ./kustomize edit set image aunews-scrapy=${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
