name: Build and deploy spiders

on:
  workflow_dispatch:
  push:
    paths:
    - 'crawler/**'

env:
  IMAGE: aunews-scrapy
  DEPLOYMENT_NAME: scrapy-deployment

defaults:
  run:
    shell: bash
    working-directory: ./crawler

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy Web API
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.LINODE_KUBE_CONFIG }}

    # Build the Docker image
    - name: Build Docker image
      run: |-
        docker build --tag ausnews/spiders:${{ github.sha }} .
        docker push ausnews/spiders:${{ github.sha }} .

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image
    - name: Deploy
      run: |-
        ./kustomize edit set image aunews-scrapy=ausnews/spiders:${{ github.sha }} .
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
