name: Build and deploy the search engine

on:
  workflow_dispatch:
  push:
    paths:
    - 'search-engine-app/**'

defaults:
  run:
    shell: bash
    working-directory: ./search-engine-app

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.LINODE_KUBE_CONFIG }}
        
    - uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

    - name: Cache deps
      uses: actions/cache@v2
      env:
        cache-name: cache-deps
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    # Build the Docker image
    - name: Build & Deploy
      run: |-
        ./scripts/bootstrap.sh
        ./scripts/deploy.sh
