name: Build and deploy the Web API

on:
  workflow_dispatch:
  push:
    paths:
    - 'web-api/**'

env:
  DEPLOYMENT_NAME: ausnews-web-api

defaults:
  run:
    shell: bash
    working-directory: ./web-api

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy Web API
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: login to dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.LINODE_KUBE_CONFIG }}
        
    - uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64

    - name: Cache deps
      uses: actions/cache@v2
      env:
        cache-name: cache-deps
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/build.gradle.kts') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    # Build the Docker image
    - name: Build Docker image
      run: |-
        ./gradlew jibDockerBuild
        docker tag ausnews-web-api ausnews/web-api:${{ github.sha }}

    # Push the Docker image to dockerhub
    - name: Publish
      run: |-
        docker push ausnews/web-api:${{ github.sha }}

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    # Deploy the Docker image to the k8s cluster
    - name: Deploy
      run: |-
        ./kustomize edit set image ausnews-web-api=ausnews/web-api:${{ github.sha }}
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
